name: Create GitHub Release

on:
  push:
    tags:
      - 'v20*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Load release body
        id: load_body
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_BODY.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.load_body.outputs.body }}
